version: '3'

name: 'python-limit-order-book'

services:
    python-limit-order-book:
        container_name: 'python-limit-order-book'
        image: example/python-limit-order-book:latest
        build: .
        ports:
            - "5555:5555"
        volumes:
            - /python-limit-order-book-data:/python-limit-order-book-data
            #- /python-limit-order-book-data/limit_order_book_file_log.txt:/python-limit-order-book/limit_order_book_file_log.txt
        restart: unless-stopped